<a href="https://colab.research.google.com/github/Czyundream/note-of-dl/blob/main/%E6%9D%8E%E6%B2%90%E5%8A%A8%E6%89%8B%E5%AD%A6%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0note.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

张量

In [ ]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel()

12

numel=number of elements方法显示元素标量个数 shape显示长量形状

In [ ]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

深度2，三行，4列

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

torchtorch.ones()全1

In [ ]:
 x=torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
x.shape

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
x.shape

torch.Size([3, 4])

##**2.1运算部分**

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

简单运算，+，-，*，**

In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

指数运算

In [ ]:
X=torch.arange(24, dtype=torch.float32).reshape(2,3,4)
Y=torch.tensor([[[2.0,1,4,3],[1,2,3,4],[4,3,2,1]],[[5.0,2,1,3],[2,4,6,8],[8,6,4,2]]])
print(torch.cat((X, Y), dim=0)), print(torch.cat((X, Y), dim=1)),print(torch.cat((X,Y),dim=2))

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

进行张量的拼接,python语音从0开始，dim=0在二维表示行，三维表示深度，

In [ ]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

逻辑运算符构建二维张量

In [ ]:
X.sum()

tensor(66.)

对于张量中所有元素求和

##2.1.3 广播机制

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

a与b两个张量维度并不相同，相加则将它们统一为同一维度，即不足的复制。

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

##2.1.4索引与切片

In [ ]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

通过指定索引来将元素写入矩阵

In [ ]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X[0:2]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

#2.1.5 节省内存

运行Y = Y + X后，我们会发现id(Y)指向另一个位置

In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作

In [ ]:
z=torch.zeros_like(Y)
print("id(z):",id(z))
z[:]=X+Y
print("id(z):",id(z))

id(z): 139959215268976
id(z): 139959215268976


In [ ]:
before = id(X)
X += Y
id(X) == before

True

#2.1.6转换为其他python对象

In [ ]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

大小为1的张量转换为Python标量

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

#数据预处理

1.创建数据集

In [ ]:
import os

os.makedirs(os.path.join('..','data'),exist_ok=True)
data_file = os.path.join('..','data','house_tiny.csv')
with open(data_file,'w') as f:
    f.write('NumRooms,Alley,Price\n') #列名
    f.write('NA,Rave,127500\n')   #每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

从创建的CSV文件中读取原始数据集

In [ ]:
import pandas as pd

data = pd.read_csv(data_file)
print(data)

   NumRooms Alley   Price
0       NaN  Rave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000


处理缺失的数据，典型的方法，*插值*与*删除* ，首先采用插值

In [ ]:
inputs , outputs= data.iloc[:,0:2] , data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Rave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


```
data.iloc
```

代表按照index查找
```
data.loc
```
loc代表按照行列名查找元素

`mean()`代表对一列求其平均值

对于`iuput`中的类别值或者离散值，我们可以将NaN是为一个类别

In [ ]:
inputs = pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Rave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


将inputs与outputs中转换为张量形式

In [ ]:
import torch
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
X,y

(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

#线形代数的简易实现
----
##标量由只有一个元素的张量表示

In [ ]:
import torch

x = torch.tensor([3.0])
y = torch.tensor([2.0])

x + y, x * y, x / y, x ** y

(tensor([5.]), tensor([6.]), tensor([1.5000]), tensor([9.]))

向量（vector）可以视为由标量组成的列表

In [ ]:
x = torch.arange(4)
x

tensor([0, 1, 2, 3])

我们可以通过索引来访问元素

In [ ]:
x[3]   #通过索引访问元素

tensor(3)

获取张量长度

In [ ]:
len(x)    #获取张量长度

x.shape   #返回形状

torch.Size([4])

通过指定$m,n$来创建一个$m \times n$ 的矩阵

In [ ]:
A = torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

转置操作

In [ ]:
A.T

tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])

向量推广到矩阵，通过矩阵构建更多维的数据结构

In [ ]:
X = torch.arange(24).reshape(2,3,4)
X

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [ ]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
B = A.clone()    #通过分配新内存， 将A的一个副本分配给BB
A, A + B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

两个矩阵元素乘法，即*哈达玛积*（数学符号$\odot$）

In [ ]:
A * B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [ ]:
a = 2
X = torch.arange(24).reshape(2 , 3 , 4)
a + X, (a * X).shape

(tensor([[[ 2,  3,  4,  5],
          [ 6,  7,  8,  9],
          [10, 11, 12, 13]],
 
         [[14, 15, 16, 17],
          [18, 19, 20, 21],
          [22, 23, 24, 25]]]), torch.Size([2, 3, 4]))

实现计算矩阵的元素和

In [3]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

表示任意形状张量的元素和

In [ ]:
##A = torch.arange(20*2, dtype=torch.float32).reshape(2,5,4)
##A.shape, A.sum(), A

(torch.Size([2, 5, 4]), tensor(780.), tensor([[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.],
          [16., 17., 18., 19.]],
 
         [[20., 21., 22., 23.],
          [24., 25., 26., 27.],
          [28., 29., 30., 31.],
          [32., 33., 34., 35.],
          [36., 37., 38., 39.]]]))

In [ ]:
A_sum_axis1 = A.sum(axis=1)
A_sum_axis1, A_sum_axis1.shape

(tensor([[ 40,  45,  50,  55],
         [140, 145, 150, 155]]), torch.Size([2, 4]))

In [ ]:
A.sum(axis=[0,1 ]).shape    #将0，1两个维度进行降维

torch.Size([])

指定求和会“汇总”张量的轴

In [ ]:
A_sum_axis0 = A.sum(axis=0)
A_sum_axis0, A_sum_axis0.shape

(tensor([40., 45., 50., 55.]), torch.Size([4]))

平均值操作（mean或average）

In [ ]:
A.mean() , A.sum() / A.numel()      #使用【2，5，4】的高维矩阵报错，使用20代码块处的A不会报错.  解决：float32可解决，mean()要求要使用浮点数

(tensor(9.5000), tensor(9.5000))

In [ ]:
A.mean(axis=0), A.sum(axis=0) / A.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

###计算总和或均值时保持轴数不变，以便应用广播机制

In [ ]:
sum_A1 = A.sum(axis=1, keepdim=True)     #应用广播机制

sum_A2 = A.sum(axis=1)

print(sum_A1, sum_A1.shape)
print(sum_A2, sum_A2.shape)

tensor([[ 6.],
        [22.],
        [38.],
        [54.],
        [70.]]) torch.Size([5, 1])
tensor([ 6., 22., 38., 54., 70.]) torch.Size([5])


###沿某一个轴计算A元素的累积总和

In [ ]:
A.cumsum(axis=0)  

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  6.,  8., 10.],
        [12., 15., 18., 21.],
        [24., 28., 32., 36.],
        [40., 45., 50., 55.]])

###点积

1.点积是相同位置的按元素乘积的和

In [5]:
import torch
y = torch.ones(4, dtype=torch.float32)
x, y, torch.dot(x, y), y.shape  #点积等价于先元素乘法再求和

(tensor([0., 1., 2., 3.]),
 tensor([1., 1., 1., 1.]),
 tensor(6.),
 torch.Size([4]))

2.矩阵的向量积$Ax$是一个长度为$m$的列向量,其第$i$个元素是点积$a_{i}^{T}x$

In [6]:
A = torch.arange(20, dtype=torch.float32).reshape(5,4)
A.shape, x.shape, torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

$AB$矩阵乘法

In [7]:
B = torch.ones(4,3)
B, torch.mm(A,B)

(tensor([[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]), tensor([[ 6.,  6.,  6.],
         [22., 22., 22.],
         [38., 38., 38.],
         [54., 54., 54.],
         [70., 70., 70.]]))

$L_{2}$范数是向量元素平方和的平方根：
$||x||_{2}=\sqrt{\sum_{i=1}^{n} x_{i}^{2}}$

In [9]:
u = torch.tensor([3.0, -4.0])

u.shape, torch.norm(u)

(torch.Size([2]), tensor(5.))

$L_{1}$范数是向量元素绝对值之和：
$||x||_{1}=\sum_{i=1}^{n} |x|$

In [10]:
torch.abs(u).sum()

tensor(7.)

矩阵的$F$范数，矩阵元素的平方和的平方根：$||X||_{F}=\sqrt{\sum_{i=1}^{m} \sum_{j=1}^{n}x_{ij}^{2}} $

In [11]:
torch.norm(torch.ones(4, 9))

tensor(6.)

#矩阵计算

###梯度
---
梯度指向值变化最大的方向


###自动求导
---
原理来源于链式法则、计算机用计算图来实现，Tensflowflow、mxnet显示构造
pytorch、mxnet也有隐式构造。

自动求导的实现

In [10]:
import torch

In [11]:
x = torch.arange(4.0)
x.requires_grad_(True)  #等价于 x = torch.arange(4.0, requires_grad=True)
x.grad  #默认值为None

In [12]:
y = 2 * torch.dot(x, x)
y

tensor(28., grad_fn=<MulBackward0>)

通过调用反向传播函数来自动计算$y$关于$x$每个分量的梯度

In [13]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [14]:
x.grad == 4 * x

tensor([True, True, True, True])

计算$x$的另一个函数

In [15]:
# 默认情况下，PyTorch会累积梯度，需要清除之前的值
#pytorch中_表示重写这个内容
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

对于深度学习，我们的目的不是计算微分矩阵，而是批量计算每个样本单独计算的偏导数之和。

In [16]:
# 对于非标量调用'backward'需要传入一个'gradient'参数，该参数指定微分函数关于self的梯度
x.grad.zero_()
y = x * x
#等价于y.backward(torch.ones(len(x)))
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

将某些计算