<a href="https://colab.research.google.com/github/Czyundream/note-of-dl/blob/main/%E6%9D%8E%E6%B2%90%E5%8A%A8%E6%89%8B%E5%AD%A6%E6%B7%B1%E5%BA%A6%E5%AD%A6%E4%B9%A0test1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch

张量

In [ ]:
x=torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
x.shape

torch.Size([12])

In [ ]:
x.numel()

12

numel=number of elements方法显示元素标量个数 shape显示长量形状

In [ ]:
x.reshape(3,4)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

深度2，三行，4列

In [ ]:
torch.zeros(2,3,4)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

torchtorch.ones()全1

In [ ]:
 x=torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
x.shape

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [ ]:
x.shape

torch.Size([3, 4])

##**2.1运算部分**

In [ ]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y  # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

简单运算，+，-，*，**

In [ ]:
torch.exp(x)

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

指数运算

In [ ]:
X=torch.arange(24, dtype=torch.float32).reshape(2,3,4)
Y=torch.tensor([[[2.0,1,4,3],[1,2,3,4],[4,3,2,1]],[[5.0,2,1,3],[2,4,6,8],[8,6,4,2]]])
print(torch.cat((X, Y), dim=0)), print(torch.cat((X, Y), dim=1)),print(torch.cat((X,Y),dim=2))

In [ ]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

进行张量的拼接,python语音从0开始，dim=0在二维表示行，三维表示深度，

In [ ]:
X==Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

逻辑运算符构建二维张量

In [ ]:
X.sum()

tensor(66.)

对于张量中所有元素求和

##2.1.3 广播机制

In [ ]:
 a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

a与b两个张量维度并不相同，相加则将它们统一为同一维度，即不足的复制。

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

##2.1.4索引与切片

In [ ]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

通过指定索引来将元素写入矩阵

In [ ]:
X[1,2]=9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X[0:2]=12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

#2.1.5 节省内存

运行Y = Y + X后，我们会发现id(Y)指向另一个位置

In [ ]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作

In [ ]:
z=torch.zeros_like(Y)
print("id(z):",id(z))
z[:]=X+Y
print("id(z):",id(z))

id(z): 139959215268976
id(z): 139959215268976


In [ ]:
before = id(X)
X += Y
id(X) == before

True

#2.1.6转换为其他python对象

In [ ]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)